<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Наши партнёры и клиенты - Компания \"ТермоФасад\"");
$APPLICATION->SetPageProperty("title", "Наши партнеры, поставщики материалов для фасадных работ");
$APPLICATION->SetTitle("Партнёры и клиенты");
?><div class="tb30-bottom">
	<div class="bxr-list">
		<h1>Наши партнеры</h1>
	</div>
	 <?$APPLICATION->IncludeComponent(
	"bxready2:block.list",
	".default",
	Array(
		"ACTIVE_DATE_FORMAT" => "j F Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BXREADY_COLLECTION_DRAW" => "empty",
		"BXREADY_ELEMENT_ADDCLASS" => "",
		"BXREADY_ELEMENT_DRAW" => "image.v1",
		"BXREADY_ELEMENT_EXT_PARAMS" => "arrExtParams",
		"BXREADY_LIST_BOOTSTRAP_GRID_STYLE" => "12",
		"BXREADY_LIST_HIDE_MOBILE_SLIDER_ARROWS" => "Y",
		"BXREADY_LIST_HIDE_MOBILE_SLIDER_AUTOSCROLL" => "N",
		"BXREADY_LIST_HIDE_SLIDER_ARROWS" => "Y",
		"BXREADY_LIST_LG_CNT" => "4",
		"BXREADY_LIST_MD_CNT" => "4",
		"BXREADY_LIST_PAGE_BLOCK_TITLE" => "",
		"BXREADY_LIST_PAGE_BLOCK_TITLE_GLYPHICON" => "",
		"BXREADY_LIST_SLIDER" => "N",
		"BXREADY_LIST_SLIDER_MARKERS" => "N",
		"BXREADY_LIST_SM_CNT" => "6",
		"BXREADY_LIST_TYPES" => "elements",
		"BXREADY_LIST_VERTICAL_SLIDER_MODE" => "N",
		"BXREADY_LIST_XS_CNT" => "12",
		"BXREADY_SECTION_DRAW" => "empty",
		"BXREADY_USER_TYPES" => "N",
		"BXREADY_USE_ELEMENTCLASS" => "Y",
		"BXREADY_VERTICAL_ALIGN" => "Y",
		"BXR_COLOR_TYPE" => "white_border",
		"BXR_ELEMENT_HEIGHT" => "150",
		"BXR_ELEMENT_MAX_HEIGHT" => "290",
		"BXR_ELEMENT_REGIME" => "normal",
		"BXR_ELEMENT_WIDTH" => "90",
		"BXR_PRST_COLOR_TYPE" => "gray",
		"BXR_PRST_ELEMENT_HEIGHT" => "140",
		"BXR_PRST_ELEMENT_REGIME" => "normal",
		"BXR_PRST_ELEMENT_WIDTH" => "100",
		"BXR_PRST_GRAYSCALE" => "N",
		"BXR_PRST_IMAGE_SIZE" => "50",
		"BXR_PRST_IMAGE_TYPE" => "gray",
		"BXR_PRST_SHOW_BORDER" => "Y",
		"BXR_PRST_SHOW_NAME" => "Y",
		"BXR_PRST_USE_BACKGROUND" => "Y",
		"BXR_SHOW_BORDER" => "Y",
		"BXR_SHOW_NAME" => "Y",
		"BXR_USE_BACKGROUND" => "Y",
		"BXR_USE_HREF" => "N",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => ".default",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(0=>"ID",1=>"CODE",2=>"XML_ID",3=>"TAGS",4=>"SORT",5=>"PREVIEW_TEXT",6=>"PREVIEW_PICTURE",7=>"DETAIL_TEXT",8=>"DETAIL_PICTURE",9=>"DATE_ACTIVE_FROM",10=>"ACTIVE_FROM",11=>"DATE_ACTIVE_TO",12=>"ACTIVE_TO",13=>"SHOW_COUNTER",14=>"SHOW_COUNTER_START",15=>"IBLOCK_TYPE_ID",16=>"IBLOCK_ID",17=>"IBLOCK_CODE",18=>"IBLOCK_NAME",19=>"IBLOCK_EXTERNAL_ID",20=>"DATE_CREATE",21=>"CREATED_BY",22=>"CREATED_USER_NAME",23=>"TIMESTAMP_X",24=>"MODIFIED_BY",25=>"USER_NAME",26=>"",),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "21",
		"IBLOCK_TYPE" => "content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "100",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(0=>"",1=>"",),
		"SET_BROWSER_TITLE" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC"
	)
);?>
</div><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>