<? global $APPLICATION, $arTopMenu;?>
<div class="bxr-full-width bxr-menuline hidden-xs hidden-sm">
    <?$APPLICATION->IncludeComponent(
	"alexkova.business:menu", 
	"version_v1", 
	array(
		"COMPONENT_TEMPLATE" => "version_v1", 
		"ROOT_MENU_TYPE" => "top",
		"MENU_CACHE_TYPE" => "N",
		"MENU_CACHE_TIME" => "3600",
		"MENU_CACHE_USE_GROUPS" => "N",
		"MENU_CACHE_GET_VARS" => array(
		),
		"MAX_LEVEL" => "4",
		"CHILD_MENU_TYPE" => "left",
		"USE_EXT" => "Y",
		"DELAY" => "N",
		"ALLOW_MULTI_SELECT" => "N",
		"SHOW_TREE" => "Y",
		"FULL_WIDTH" => isset($arTopMenu["FULL_WIDTH"]) ? $arTopMenu["FULL_WIDTH"] : "Y",
		"COMPACT_MODE_MENU" => "Y",
		"SEARCH_FORM" => isset($arTopMenu["SEARCH_FORM"]) ? $arTopMenu["SEARCH_FORM"] : "Y",
		"STYLE_MENU_HOVER" => isset($arTopMenu["STYLE_MENU_HOVER"]) ? $arTopMenu["STYLE_MENU_HOVER"] : "colored_light",
		"ICO_TOP_MENU" => isset($arTopMenu["PICTURE_SECTION"]) ? $arTopMenu["PICTURE_SECTION"] : "N",
                "PICTURE_SECTION" => isset($arTopMenu["PICTURE_SECTION_HOVER"]) ? $arTopMenu["PICTURE_SECTION_HOVER"] : "N",
                "PICTURE_CATEGARIES" => isset($arTopMenu["PICTURE_CATEGARIES"]) ? $arTopMenu["PICTURE_CATEGARIES"] : "N",
		"VIEW_SUBSECTION" => "LINE",
		"MENU_HOVER_RESOLUTION_LG" => "",
		"MENU_HOVER_RESOLUTION_MD" => "",
		"MENU_HOVER_RESOLUTION_SM" => "",
		"MENU_HOVER_RESOLUTION_XS" => "",
		"PAGE" => "#SITE_DIR#search/",
		"NUM_CATEGORIES" => "1",
		"TOP_COUNT" => "5",
		"ORDER" => "date",
		"USE_LANGUAGE_GUESS" => "Y",
		"CHECK_DATES" => "N",
		"SHOW_OTHERS" => "N",
		"SHOW_INPUT" => "Y",
		"INPUT_ID" => "title-search-input-menu-1",
		"CONTAINER_ID" => "title-search-menu-1",
		"PRICE_CODE" => array(
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "200",
		"SHOW_PREVIEW" => "Y",
		"CONVERT_CURRENCY" => "Y",
		"PREVIEW_WIDTH" => "54",
		"PREVIEW_HEIGHT" => "54",
		"BIG_MODE_MENU" => "N",
		"FULL_WIDTH_MENU_HOVER" => "N",
		"TEXT_MOBIL_MENU" => "",
		"TEMPLATE_MENU_HOVER" => isset($arTopMenu["TEMPLATE_MENU_HOVER"]) ? $arTopMenu["TEMPLATE_MENU_HOVER"] : "classic",
		"HOVER_MENU_COL_LG" => isset($arTopMenu["HOVER_MENU_COL_LG"]) ? $arTopMenu["HOVER_MENU_COL_LG"] : "3",
		"HOVER_MENU_COL_MD" => isset($arTopMenu["HOVER_MENU_COL_MD"]) ? $arTopMenu["HOVER_MENU_COL_MD"] : "2",
		"HOVER_MENU_COL_SM" => "1",
		"HOVER_MENU_COL_XS" => "1",
		"CATEGORY_0_TITLE" => "",
		"CATEGORY_0" => array(
			0 => "no",
		),
		"CATEGORY_0_iblock_catalog" => array(
		),
		"COLOR_MENU" => isset($arTopMenu["STYLE_MENU"]) ? $arTopMenu["STYLE_MENU"] :"light",
		"FONT_MENU" => isset($arTopMenu["FONT_MENU"]) ? $arTopMenu["FONT_MENU"] : "normal",
		"INDENT_ITEMS_MENU" => "normal",
		"STRETCH_MENU" => "Y",
		/*"ICO_TOP_MENU" => "N",*/
		"ICO_TOP_MENU_COLOR_1" => isset($arTopMenu["ICO_TOP_MENU_COLOR_1"]) ? $arTopMenu["ICO_TOP_MENU_COLOR_1"] : "light",
		"ICO_TOP_MENU_COLOR_2" => isset($arTopMenu["ICO_TOP_MENU_COLOR_2"]) ? $arTopMenu["ICO_TOP_MENU_COLOR_2"] : "light",
		"ICO_HOVER_MENU_COLOR_1" => isset($arTopMenu["ICO_TOP_MENU_HOVER_COLOR_1"]) ? $arTopMenu["ICO_TOP_MENU_HOVER_COLOR_1"] : "color",
		"ICO_HOVER_MENU_COLOR_2" => isset($arTopMenu["ICO_TOP_MENU_HOVER_COLOR_2"]) ? $arTopMenu["ICO_TOP_MENU_HOVER_COLOR_2"] : "light"
	),
	false
);?>
</div>
