<? global $APPLICATION;?>
<div class="bxr-full-width bxr-menuline">
    <?$APPLICATION->IncludeComponent(
	"alexkova.business:menu", 
	"version_v1", 
	array(
		"COMPONENT_TEMPLATE" => "version_v1",
		"ROOT_MENU_TYPE" => "top",
		"MENU_CACHE_TYPE" => "N",
		"MENU_CACHE_TIME" => "3600",
		"MENU_CACHE_USE_GROUPS" => "N",
		"MENU_CACHE_GET_VARS" => array(
		),
		"MAX_LEVEL" => "4",
		"CHILD_MENU_TYPE" => "left",
		"USE_EXT" => "Y",
		"DELAY" => "N",
		"ALLOW_MULTI_SELECT" => "N",
		"SHOW_TREE" => "Y",
		"FULL_WIDTH" => "Y",
		"COMPACT_MODE_MENU" => "Y",
		"SEARCH_FORM" => "Y",
		"STYLE_MENU_HOVER" => "colored_light",
		"PICTURE_CATEGARIES" => "N",
		"PICTURE_SECTION" => "N",
		"VIEW_SUBSECTION" => "LINE",
		"MENU_HOVER_RESOLUTION_LG" => "",
		"MENU_HOVER_RESOLUTION_MD" => "",
		"MENU_HOVER_RESOLUTION_SM" => "",
		"MENU_HOVER_RESOLUTION_XS" => "",
		"PAGE" => "/search/",
		"NUM_CATEGORIES" => "1",
		"TOP_COUNT" => "5",
		"ORDER" => "date",
		"USE_LANGUAGE_GUESS" => "Y",
		"CHECK_DATES" => "N",
		"SHOW_OTHERS" => "N",
		"SHOW_INPUT" => "Y",
		"INPUT_ID" => "title-search-input-menu-1",
		"CONTAINER_ID" => "title-search-menu-1",
		"PRICE_CODE" => array(
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "200",
		"SHOW_PREVIEW" => "Y",
		"CONVERT_CURRENCY" => "Y",
		"PREVIEW_WIDTH" => "54",
		"PREVIEW_HEIGHT" => "54",
		"BIG_MODE_MENU" => "N",
		"FULL_WIDTH_MENU_HOVER" => "N",
		"TEXT_MOBIL_MENU" => "Меню",
		"TEMPLATE_MENU_HOVER" => "classic",
		"HOVER_MENU_COL_LG" => "3",
		"HOVER_MENU_COL_MD" => "2",
		"HOVER_MENU_COL_SM" => "1",
		"HOVER_MENU_COL_XS" => "1",
		"CATEGORY_0_TITLE" => "Товары",
		"CATEGORY_0" => array(
			0 => "iblock_catalog",
		),
		"CATEGORY_0_iblock_catalog" => array(
		),
		"COLOR_MENU" => "light",
		"FONT_MENU" => "normal",
		"INDENT_ITEMS_MENU" => "normal",
		"STRETCH_MENU" => "Y",
		"ICO_TOP_MENU" => "N",
		"ICO_TOP_MENU_COLOR_1" => "light",
		"ICO_TOP_MENU_COLOR_2" => "light",
		"ICO_HOVER_MENU_COLOR_1" => "color",
		"ICO_HOVER_MENU_COLOR_2" => "light"
	),
	false
);?>
</div>
